language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
rvm:
  - 2.2.0
before_script:
  - npm install
  - npm install -g bower
  - bower install
script:
  - CODECLIMATE_REPO_TOKEN=6379678c9245d7c0695b4a011bac7e58e9a59ee91e5486af9e3ce494d3d7f9f8 bundle exec rspec
  - npm test
  - npm run gulp silent build
  - npm run gulp silent prod build
env:
  global:
    - secure: cB2TT8OlHvUW9EwWVtBgXhNxCQrUbMLHDqvZrIgK9Oa6Nd+KQp1SgYHYLeQQzRxxp62K3k6jp+xJk+YQgj33Oh0k9YQxT1A95iCzaNvs505qWZHqRzg+sWTXTm0BLb3kzE5r3lqpiwfpYGTivEh8xbh+WZ+4T42tSMC+lUyuDk4=
    - secure: Id68bv85yig92Xd6+2MqDFOZLxvR11BKSveZ+wpbgwSspFp/ol7sL7ut8cB39Uw3Rr2zB6ijO1fW1tcl3zJLYoWdqFpebPoTIy3bp76AeKaunNe0Dl6HgmQAq/UsDYnO1i+rp0Mj7hpZIpuxL1rqpNKY9ypJ317pTbcpBDnBkh8=
after_success:
  - openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
  - sh deploy.sh
