language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
rvm:
  - 2.2.0
before_script:
  - npm install
  - npm install -g bower
  - bower install
script:
  - CODECLIMATE_REPO_TOKEN=6379678c9245d7c0695b4a011bac7e58e9a59ee91e5486af9e3ce494d3d7f9f8 bundle exec rspec
  - npm test
  - npm run gulp run-e2e --nosound
  - npm run gulp run-e2e --nosound --prod
env:
  global:
    - secure: gx4ZFVVi++vT5oQusrzLasy/szWmrcd29MrkO1n6iYeh6wVHMqNUPlW9f8yfua7wg5Gfg5Uvien0RxhdzY7ov4V6qGk/IXSMGFbECLZB2neOCWci86BZQ+cgL4ekvbN+JucrWC48dTDlFPwltUWHaDCpm3V7Y6/+3rTp8l5t4Ws=
    - secure: fVRHp8RNn4e3fLg2iRyZiUk+UVLqx+m65ClADT5a9Hw4ea9jvu1v+5t3j7Im/vzgl9T6EE5DkuAPuJYHAlq0PK1lUH1FV4+yv4XP7IOaqU659nY1oxxAsIeByfNrh1qZob9XVyDlYxEXRcHaZqy6l/dmD+IKHj5p+KZHTzMovQE=
after_success:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
  - openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
  - sh deploy.sh
