language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
rvm:
  - 2.2.0
env:
  global:
    - SAUCE_USERNAME=endaaman
    - SAUCE_ACCESS_KEY=a8249603-9c1f-4f7d-83a7-ac85e7a6389f
    - LOGS_DIR=/tmp/hokui.net-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - secure: gx4ZFVVi++vT5oQusrzLasy/szWmrcd29MrkO1n6iYeh6wVHMqNUPlW9f8yfua7wg5Gfg5Uvien0RxhdzY7ov4V6qGk/IXSMGFbECLZB2neOCWci86BZQ+cgL4ekvbN+JucrWC48dTDlFPwltUWHaDCpm3V7Y6/+3rTp8l5t4Ws=
    - secure: fVRHp8RNn4e3fLg2iRyZiUk+UVLqx+m65ClADT5a9Hw4ea9jvu1v+5t3j7Im/vzgl9T6EE5DkuAPuJYHAlq0PK1lUH1FV4+yv4XP7IOaqU659nY1oxxAsIeByfNrh1qZob9XVyDlYxEXRcHaZqy6l/dmD+IKHj5p+KZHTzMovQE=
before_script:
  - mkdir -p $LOGS_DIR
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update
  - npm install -g bower
  - bower install
  - sh scripts/sauce_connect_setup.sh
  - sh scripts/wait_for_browser_provider.sh
script:
  - CODECLIMATE_REPO_TOKEN=6379678c9245d7c0695b4a011bac7e58e9a59ee91e5486af9e3ce494d3d7f9f8 bundle exec rspec
  - npm test
  - ./node_modules/gulp/bin/gulp.js run-e2e --nosound
  - ./node_modules/gulp/bin/gulp.js run-e2e --nosound --prod
after_success:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
  # - sh scripts/print_logs.sh
  - openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
  - sh scripts/deploy.sh
