language: node_js
node_js:
  - 0.10
cache:
  directories:
    - node_modules
rvm:
  - 2.2.0
env:
  global:
    - SAUCE_USERNAME=endaaman
    - SAUCE_ACCESS_KEY=f9836a7e58ca-7a38-d7f4-f1c9-3069428a
    - LOGS_DIR=/tmp/hokui.net-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
before_script:
  - mkdir -p $LOGS_DIR
  - node_modules/protractor/bin/webdriver-manager update
  - npm install -g bower
  - bower install
  - sh scripts/sauce_connect_setup.sh
  - sh scripts/wait_for_browser_provider.sh
script:
  - npm test
  - sh e2e_on_sauce.sh
after_success:
  - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
